name: sync-labs-to-feishu

on:
  # push:
  #   branches:
  #     - master
  #   paths:
  #     - "**/index.json"
  workflow_dispatch:

jobs:
  sync:
    if: github.repository_owner == 'labex-labs'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Sync to Feishu
        env:
          APP_ID: ${{ secrets.APP_ID }}
          APP_SECRET: ${{ secrets.APP_SECRET }}
        run: |
          pip install requests
          pip install jsonschema
          wget https://cdn.jsdelivr.net/gh/labex-labs/common-scripts@latest/schema.json
          wget https://cdn.jsdelivr.net/gh/labex-labs/common-scripts@latest/actions/sync-labs-to-feishu.py
          python sync-labs-to-feishu.py --appid "$APP_ID" --appsecret "$APP_SECRET" --repo $GITHUB_REPOSITORY --schema schema.json